In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from collections import Counter
import warnings
warnings.filterwarnings("ignore")

# reading csv files
data =  pd.read_csv(r'D:\HomeWork\Machine Learning\dataset\data_train.csv', sep=",",header = None)
test =  pd.read_csv(r'D:\HomeWork\Machine Learning\dataset\data_test.csv', sep=",",header = None)

goalTest = test.pop(16)
dfTest = test.copy()

goal = data.pop(16)
df = data.copy()

data.head()

   0    1   2    3    4    5    6    7   8   9    10  11   12  13   14  15
0  47  100  27   81   57   37   26    0   0  23   56  53  100  90   40  98
1   0   89  27  100   42   75   29   45  15  15   37   0   69   2  100   6
2   0   57  31   68   72   90  100  100  76  75   50  51   28  25   16   0
3   0  100   7   92    5   68   19   45  86  34  100  45   74  23   67   0
4   0   67  49   83  100  100   81   80  60  60   40  40   33  20   47   0

In [2]:
def calculateForest(X_train , y_train ,  estimators):
    Forest = RandomForestClassifier(n_estimators = estimators)
    Forest.fit(X_train, y_train)
    return Forest

In [3]:
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
      
    print("Confusion Matrix: \n",
        confusion_matrix(y_test, y_pred))
      
    print ("\n Accuracy : \n",
    accuracy_score(y_test,y_pred)*100)
    
    print ("\n Precision : \n",
    precision_score(y_test,y_pred, average='macro')*100)

In [5]:
Forest = calculateForest(df , goal  , 15)
y_pred = Forest.predict(dfTest)

cal_accuracy(goalTest,y_pred)

Confusion Matrix:
 [[345   0   0   0   0   0   0   0  18   0]
 [  0 329  33   1   0   0   0   1   0   0]
 [  0   5 357   0   0   0   0   2   0   0]
 [  0   3   0 332   0   0   0   0   0   1]
 [  0   0   0   0 364   0   0   0   0   0]
 [  0   0   0   9   1 307   0   0   2  16]
 [  1   0   0   1   0   0 334   0   0   0]
 [  0  15   2   2   2   0   1 327   0  15]
 [  1   0   0   0   0   2   0   0 333   0]
 [  0   3   0   1   0   1   0   2   1 328]]

 Accuracy :
 95.9405374499714

 Precision :
 96.07140687934361